version: '3'
services:
  app:
    build: .
    container_name: web
    volumes:
      - .:/app:cached
      - front_node_modules:/app/node_modules
    ports:
      - "3000:3000"
    environment:
      - HOST=0.0.0.0
    tty: true
volumes:
  front_node_modules: